export const data = [
	{
		token: '111111',
		cash: '2',
		image: '',
		username: 'Timur',
		password: '111',
		name: 'Тимур',
		lastName: 'Тимуров',
		desription: 'Информация о Тимуре',
		finishedModules: ['Вводный модуль', 'Основы программирования Scratch Jr'],
		upcomingModules: [
			'CodeMonkey. Развиваем логику',
			'Видеоблогинг',
			'Нейросети',
		],
	},
	{
		token: '222222',
		cash: '2000',
		image: '',
		username: 'Misha',
		password: '111',
		name: 'Михайл',
		lastName: 'Михайлов',
		desription: 'Информация о Мише',
		finishedModules: [
			'Вводный модуль',
			'Основы программирования Scratch Jr',
			'CodeMonkey. Развиваем логику',
		],
		upcomingModules: ['Видеоблогинг', 'Нейросети'],
	},
	{
		token: '333333',
		cash: '1358',
		image: '',
		username: 'Dima',
		password: '111',
		name: 'Дима',
		lastName: 'Дмитриев',
		desription: 'Информация о Диме',
		finishedModules: [],
		upcomingModules: [
			'Вводный модуль',
			'Основы программирования Scratch Jr',
			'CodeMonkey. Развиваем логику',
			'Видеоблогинг',
			'Нейросети',
		],
	},
]
